version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/tests/core/UnitTest/Design/CVE/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "maven"
    directory: "/tests/core/UnitTest/Design/XML"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "h2database"
      - versions: [ ">=1.4.0" ]
